# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 14 */7 * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: ItzDabbzz/metrics
        uses: felipecrs/metrics@master
        with:
          use_prebuilt_image: no
          token: ${{ secrets.METRICS_TOKEN }}
          user: ItzDabbzz
          base: header, activity, community, repositories, metadata
          config_order: introduction, base.header, base.activity+community, base.repositories, base.metadata, music, steam, wakatime, notable, followup, reactions, people, languages, activity
          base_hireable: yes
          base_indepth: yes
          config_display: large
          config_octicon: yes
          config_timezone: America/Chicago
          config_twemoji: yes
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKA_TOKEN }}
          plugin_wakatime_days: 365
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: ItzDabbzz
          plugin_activity: yes
          plugin_activity_days: 360
          plugin_activity_filter: push, issue, pr, review, comment, wiki, fork, public, member, release, ref/create, ref/delete
          plugin_activity_limit: 10
          plugin_activity_load: 10
          plugin_activity_timestamps: yes
          plugin_activity_visibility: all
          plugin_followup: yes
          plugin_followup_sections: all
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_limit: 0
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          repositories: 100
          repositories_affiliations: owner, collaborator, organization_member
          repositories_forks: no
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_people: yes
          plugin_people_types: owner, collaborator, organization_member
          plugin_reactions: yes
          plugin_music: yes
          plugin_music_mode: top
          plugin_music_top_type: tracks
          plugin_music_provider: youtube
          plugin_music_token: ${{ secrets.YOUTUBE_MUSIC_TOKENS }}
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "76561198095362587"
          plugin_anilist: yes
          plugin_anilist_user: ItzDabbzz
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 3
