name: ReadMe

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
              with:
                  persist-credentials: false
                  fetch-depth: 0

            - name: Create README.md
              uses: ItzDabbzz/profile-readme@v0.2.1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  username: ItzDabbzz
                  wakatime_key: ${{ secrets.WAKATIME_KEY }}

            - name: Commit & Push changes
              uses: actions-js/push@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}

on:
    push: { branches: ["master", "main"] }
    schedule: [{ cron: "0 14 */7 * *" }]
    workflow_dispatch:
